// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: api/v1/sexton.proto

package sextonv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sexton_Status_FullMethodName = "/sexton.v1.Sexton/Status"
	Sexton_Sync_FullMethodName   = "/sexton.v1.Sexton/Sync"
	Sexton_Snooze_FullMethodName = "/sexton.v1.Sexton/Snooze"
	Sexton_Resume_FullMethodName = "/sexton.v1.Sexton/Resume"
)

// SextonClient is the client API for Sexton service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SextonClient interface {
	// get the current status of all monitored repos (or a specific one)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// trigger an immediate sync cycle for a repo
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// snooze a repo for a specified duration
	Snooze(ctx context.Context, in *SnoozeRequest, opts ...grpc.CallOption) (*SnoozeResponse, error)
	// resume a snoozed or halted repo
	Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error)
}

type sextonClient struct {
	cc grpc.ClientConnInterface
}

func NewSextonClient(cc grpc.ClientConnInterface) SextonClient {
	return &sextonClient{cc}
}

func (c *sextonClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Sexton_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sextonClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, Sexton_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sextonClient) Snooze(ctx context.Context, in *SnoozeRequest, opts ...grpc.CallOption) (*SnoozeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnoozeResponse)
	err := c.cc.Invoke(ctx, Sexton_Snooze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sextonClient) Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeResponse)
	err := c.cc.Invoke(ctx, Sexton_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SextonServer is the server API for Sexton service.
// All implementations must embed UnimplementedSextonServer
// for forward compatibility.
type SextonServer interface {
	// get the current status of all monitored repos (or a specific one)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// trigger an immediate sync cycle for a repo
	Sync(context.Context, *SyncRequest) (*SyncResponse, error)
	// snooze a repo for a specified duration
	Snooze(context.Context, *SnoozeRequest) (*SnoozeResponse, error)
	// resume a snoozed or halted repo
	Resume(context.Context, *ResumeRequest) (*ResumeResponse, error)
	mustEmbedUnimplementedSextonServer()
}

// UnimplementedSextonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSextonServer struct{}

func (UnimplementedSextonServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedSextonServer) Sync(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedSextonServer) Snooze(context.Context, *SnoozeRequest) (*SnoozeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Snooze not implemented")
}
func (UnimplementedSextonServer) Resume(context.Context, *ResumeRequest) (*ResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedSextonServer) mustEmbedUnimplementedSextonServer() {}
func (UnimplementedSextonServer) testEmbeddedByValue()                {}

// UnsafeSextonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SextonServer will
// result in compilation errors.
type UnsafeSextonServer interface {
	mustEmbedUnimplementedSextonServer()
}

func RegisterSextonServer(s grpc.ServiceRegistrar, srv SextonServer) {
	// If the following call panics, it indicates UnimplementedSextonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sexton_ServiceDesc, srv)
}

func _Sexton_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SextonServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sexton_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SextonServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sexton_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SextonServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sexton_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SextonServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sexton_Snooze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnoozeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SextonServer).Snooze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sexton_Snooze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SextonServer).Snooze(ctx, req.(*SnoozeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sexton_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SextonServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sexton_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SextonServer).Resume(ctx, req.(*ResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sexton_ServiceDesc is the grpc.ServiceDesc for Sexton service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sexton_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sexton.v1.Sexton",
	HandlerType: (*SextonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Sexton_Status_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _Sexton_Sync_Handler,
		},
		{
			MethodName: "Snooze",
			Handler:    _Sexton_Snooze_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _Sexton_Resume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/sexton.proto",
}
