// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/v1/sexton.proto

package sextonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"` // optional; empty = all repos
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_v1_sexton_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sexton_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sexton_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type RepoStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Path            string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	State           string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // watching, syncing, snoozed, halted
	Branch          string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	LastSync        string                 `protobuf:"bytes,4,opt,name=last_sync,json=lastSync,proto3" json:"last_sync,omitempty"`                      // RFC3339 timestamp
	LastCommit      string                 `protobuf:"bytes,5,opt,name=last_commit,json=lastCommit,proto3" json:"last_commit,omitempty"`                // short SHA
	Error           string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                                            // populated when halted
	SnoozeRemaining string                 `protobuf:"bytes,7,opt,name=snooze_remaining,json=snoozeRemaining,proto3" json:"snooze_remaining,omitempty"` // populated when snoozed
	Name            string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RepoStatus) Reset() {
	*x = RepoStatus{}
	mi := &file_api_v1_sexton_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoStatus) ProtoMessage() {}

func (x *RepoStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sexton_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoStatus.ProtoReflect.Descriptor instead.
func (*RepoStatus) Descriptor() ([]byte, []int) {
	return file_api_v1_sexton_proto_rawDescGZIP(), []int{1}
}

func (x *RepoStatus) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RepoStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RepoStatus) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *RepoStatus) GetLastSync() string {
	if x != nil {
		return x.LastSync
	}
	return ""
}

func (x *RepoStatus) GetLastCommit() string {
	if x != nil {
		return x.LastCommit
	}
	return ""
}

func (x *RepoStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RepoStatus) GetSnoozeRemaining() string {
	if x != nil {
		return x.SnoozeRemaining
	}
	return ""
}

func (x *RepoStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repos         []*RepoStatus          `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_v1_sexton_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sexton_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sexton_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResponse) GetRepos() []*RepoStatus {
	if x != nil {
		return x.Repos
	}
	return nil
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"` // required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_api_v1_sexton_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sexton_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sexton_proto_rawDescGZIP(), []int{3}
}

func (x *SyncRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_api_v1_sexton_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sexton_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sexton_proto_rawDescGZIP(), []int{4}
}

func (x *SyncResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SnoozeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`         // required
	Duration      string                 `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"` // e.g. "30m", "1h"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnoozeRequest) Reset() {
	*x = SnoozeRequest{}
	mi := &file_api_v1_sexton_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnoozeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnoozeRequest) ProtoMessage() {}

func (x *SnoozeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sexton_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnoozeRequest.ProtoReflect.Descriptor instead.
func (*SnoozeRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sexton_proto_rawDescGZIP(), []int{5}
}

func (x *SnoozeRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *SnoozeRequest) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

type SnoozeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Expires       string                 `protobuf:"bytes,2,opt,name=expires,proto3" json:"expires,omitempty"` // RFC3339 timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnoozeResponse) Reset() {
	*x = SnoozeResponse{}
	mi := &file_api_v1_sexton_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnoozeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnoozeResponse) ProtoMessage() {}

func (x *SnoozeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sexton_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnoozeResponse.ProtoReflect.Descriptor instead.
func (*SnoozeResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sexton_proto_rawDescGZIP(), []int{6}
}

func (x *SnoozeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SnoozeResponse) GetExpires() string {
	if x != nil {
		return x.Expires
	}
	return ""
}

type ResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"` // required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_api_v1_sexton_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sexton_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sexton_proto_rawDescGZIP(), []int{7}
}

func (x *ResumeRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type ResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeResponse) Reset() {
	*x = ResumeResponse{}
	mi := &file_api_v1_sexton_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeResponse) ProtoMessage() {}

func (x *ResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sexton_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeResponse.ProtoReflect.Descriptor instead.
func (*ResumeResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sexton_proto_rawDescGZIP(), []int{8}
}

func (x *ResumeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ResumeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_v1_sexton_proto protoreflect.FileDescriptor

const file_api_v1_sexton_proto_rawDesc = "" +
	"\n" +
	"\x13api/v1/sexton.proto\x12\tsexton.v1\"#\n" +
	"\rStatusRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\"\xe1\x01\n" +
	"\n" +
	"RepoStatus\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12\x1b\n" +
	"\tlast_sync\x18\x04 \x01(\tR\blastSync\x12\x1f\n" +
	"\vlast_commit\x18\x05 \x01(\tR\n" +
	"lastCommit\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12)\n" +
	"\x10snooze_remaining\x18\a \x01(\tR\x0fsnoozeRemaining\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\"=\n" +
	"\x0eStatusResponse\x12+\n" +
	"\x05repos\x18\x01 \x03(\v2\x15.sexton.v1.RepoStatusR\x05repos\"!\n" +
	"\vSyncRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\"8\n" +
	"\fSyncResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\rSnoozeRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\tR\bduration\":\n" +
	"\x0eSnoozeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aexpires\x18\x02 \x01(\tR\aexpires\"#\n" +
	"\rResumeRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\":\n" +
	"\x0eResumeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xfe\x01\n" +
	"\x06Sexton\x12=\n" +
	"\x06Status\x12\x18.sexton.v1.StatusRequest\x1a\x19.sexton.v1.StatusResponse\x127\n" +
	"\x04Sync\x12\x16.sexton.v1.SyncRequest\x1a\x17.sexton.v1.SyncResponse\x12=\n" +
	"\x06Snooze\x12\x18.sexton.v1.SnoozeRequest\x1a\x19.sexton.v1.SnoozeResponse\x12=\n" +
	"\x06Resume\x12\x18.sexton.v1.ResumeRequest\x1a\x19.sexton.v1.ResumeResponseB2Z0github.com/michaelquigley/sexton/api/v1;sextonv1b\x06proto3"

var (
	file_api_v1_sexton_proto_rawDescOnce sync.Once
	file_api_v1_sexton_proto_rawDescData []byte
)

func file_api_v1_sexton_proto_rawDescGZIP() []byte {
	file_api_v1_sexton_proto_rawDescOnce.Do(func() {
		file_api_v1_sexton_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_sexton_proto_rawDesc), len(file_api_v1_sexton_proto_rawDesc)))
	})
	return file_api_v1_sexton_proto_rawDescData
}

var file_api_v1_sexton_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_v1_sexton_proto_goTypes = []any{
	(*StatusRequest)(nil),  // 0: sexton.v1.StatusRequest
	(*RepoStatus)(nil),     // 1: sexton.v1.RepoStatus
	(*StatusResponse)(nil), // 2: sexton.v1.StatusResponse
	(*SyncRequest)(nil),    // 3: sexton.v1.SyncRequest
	(*SyncResponse)(nil),   // 4: sexton.v1.SyncResponse
	(*SnoozeRequest)(nil),  // 5: sexton.v1.SnoozeRequest
	(*SnoozeResponse)(nil), // 6: sexton.v1.SnoozeResponse
	(*ResumeRequest)(nil),  // 7: sexton.v1.ResumeRequest
	(*ResumeResponse)(nil), // 8: sexton.v1.ResumeResponse
}
var file_api_v1_sexton_proto_depIdxs = []int32{
	1, // 0: sexton.v1.StatusResponse.repos:type_name -> sexton.v1.RepoStatus
	0, // 1: sexton.v1.Sexton.Status:input_type -> sexton.v1.StatusRequest
	3, // 2: sexton.v1.Sexton.Sync:input_type -> sexton.v1.SyncRequest
	5, // 3: sexton.v1.Sexton.Snooze:input_type -> sexton.v1.SnoozeRequest
	7, // 4: sexton.v1.Sexton.Resume:input_type -> sexton.v1.ResumeRequest
	2, // 5: sexton.v1.Sexton.Status:output_type -> sexton.v1.StatusResponse
	4, // 6: sexton.v1.Sexton.Sync:output_type -> sexton.v1.SyncResponse
	6, // 7: sexton.v1.Sexton.Snooze:output_type -> sexton.v1.SnoozeResponse
	8, // 8: sexton.v1.Sexton.Resume:output_type -> sexton.v1.ResumeResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_sexton_proto_init() }
func file_api_v1_sexton_proto_init() {
	if File_api_v1_sexton_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_sexton_proto_rawDesc), len(file_api_v1_sexton_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_sexton_proto_goTypes,
		DependencyIndexes: file_api_v1_sexton_proto_depIdxs,
		MessageInfos:      file_api_v1_sexton_proto_msgTypes,
	}.Build()
	File_api_v1_sexton_proto = out.File
	file_api_v1_sexton_proto_goTypes = nil
	file_api_v1_sexton_proto_depIdxs = nil
}
